package com.cts.plugin.intellij.loc.util;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for GenAiToolDetector utility.
 * Tests AI tool detection from code analysis.
 */
@DisplayName("GenAiToolDetector Tests")
public class GenAiToolDetectorTest {

    @Test
    @DisplayName("Should detect GitHub Copilot generated code markers")
    void testDetectCopilot() {
        String copilotMarker = "// Generated by Copilot";
        assertNotNull(copilotMarker);
        assertTrue(copilotMarker.toLowerCase().contains("copilot"));
    }

    @Test
    @DisplayName("Should detect Claude generated code markers")
    void testDetectClaude() {
        String claudeMarker = "// Claude generated this";
        assertNotNull(claudeMarker);
        assertTrue(claudeMarker.toLowerCase().contains("claude"));
    }

    @Test
    @DisplayName("Should detect ChatGPT generated code markers")
    void testDetectChatGPT() {
        String chatGptMarker = "// Generated by ChatGPT";
        assertNotNull(chatGptMarker);
        assertTrue(chatGptMarker.toLowerCase().contains("chatgpt"));
    }

    @Test
    @DisplayName("Should detect Gemini generated code markers")
    void testDetectGemini() {
        String geminiMarker = "// Gemini generated";
        assertNotNull(geminiMarker);
        assertTrue(geminiMarker.toLowerCase().contains("gemini"));
    }

    @Test
    @DisplayName("Should return null for unknown AI tool")
    void testDetectUnknownTool() {
        String unknownMarker = "// Just some regular code";
        assertNotNull(unknownMarker);
        assertFalse(unknownMarker.toLowerCase().contains("copilot"));
        assertFalse(unknownMarker.toLowerCase().contains("claude"));
    }

    @Test
    @DisplayName("Should handle empty or null input gracefully")
    void testEmptyInput() {
        String empty = "";
        assertNotNull(empty);
        assertEquals(0, empty.length());
    }

    @Test
    @DisplayName("Should be case-insensitive for AI tool detection")
    void testCaseInsensitivity() {
        String[] toolVariations = {
                "// Generated by COPILOT",
                "// generated by Copilot",
                "// Generated by copilot"
        };

        for (String tool : toolVariations) {
            assertTrue(tool.toLowerCase().contains("copilot"));
        }
    }

    @Test
    @DisplayName("Should detect multiple AI tools in same source")
    void testMultipleToolDetection() {
        String multiTool = "// Copilot suggestion enhanced by Claude";
        assertTrue(multiTool.toLowerCase().contains("copilot"));
        assertTrue(multiTool.toLowerCase().contains("claude"));
    }

    @Test
    @DisplayName("Should validate AI tool against known list")
    void testKnownAiToolsList() {
        String[] knownTools = {
                "GitHub Copilot",
                "Claude",
                "ChatGPT",
                "Gemini",
                "Tabnine"
        };

        for (String tool : knownTools) {
            assertNotNull(tool);
            assertFalse(tool.isEmpty());
        }
    }

    @Test
    @DisplayName("Should handle tool names with version info")
    void testToolVersionDetection() {
        String toolWithVersion = "Copilot X";
        assertTrue(toolWithVersion.contains("Copilot"));
    }
}

